/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2025-05-25 21:31:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.jogoseletronicos.model.Jogo;

public final class editaJogo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.jogoseletronicos.model.Jogo");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Editar Jogo</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/header.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-light\">\r\n");
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

        Jogo jogo = (Jogo) request.getAttribute("jogo");
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-fluid py-3\">\r\n");
      out.write("        <div class=\"mx-auto\" style=\"max-width: 75%;\">\r\n");
      out.write("            <div class=\"card shadow-lg border-0 p-5\">\r\n");
      out.write("                <div class=\"row g-5 align-items-start\">\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <h1 class=\"fw-bold mb-4 fs-1 text-center\">Edição do Jogo</h1>\r\n");
      out.write("                        <form action=\"");
      out.print( request.getContextPath() );
      out.write("/editar-jogo\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("                            \r\n");
      out.write("\r\n");
      out.write("                            <div class=\"mb-4\">\r\n");
      out.write("                                <label for=\"titulo\" class=\"form-label fs-2\">Título</label>\r\n");
      out.write("                                <input type=\"text\" name=\"titulo\" id=\"titulo\" class=\"form-control form-control-lg\" value=\"");
      out.print( jogo.getTitulo() );
      out.write("\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"mb-4\">\r\n");
      out.write("                                <label for=\"desenvolvedor\" class=\"form-label fs-2\">Desenvolvedor</label>\r\n");
      out.write("                                <input type=\"text\" name=\"desenvolvedor\" id=\"desenvolvedor\" class=\"form-control form-control-lg\" value=\"");
      out.print( jogo.getDesenvolvedor() );
      out.write("\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"mb-4\">\r\n");
      out.write("                                <label for=\"anoLancamento\" class=\"form-label fs-2\">Ano de Lançamento</label>\r\n");
      out.write("                                <input type=\"text\" name=\"anoLancamento\" id=\"anoLancamento\" class=\"form-control form-control-lg\" value=\"");
      out.print( jogo.getAnoLancamento() );
      out.write("\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"mb-4\">\r\n");
      out.write("                                <label for=\"genero\" class=\"form-label fs-2\">Gênero</label>\r\n");
      out.write("                                <input type=\"text\" name=\"genero\" id=\"genero\" class=\"form-control form-control-lg\" value=\"");
      out.print( jogo.getGenero() );
      out.write("\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"mb-4\">\r\n");
      out.write("                                <label for=\"sinopse\" class=\"form-label fs-2\">Sinopse</label>\r\n");
      out.write("                                <textarea name=\"sinopse\" id=\"sinopse\" rows=\"4\" class=\"form-control form-control-lg\" required>");
      out.print( jogo.getSinopse() );
      out.write("</textarea>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"mb-4\">\r\n");
      out.write("                                <label for=\"idioma\" class=\"form-label fs-2\">Idioma</label>\r\n");
      out.write("                                <input type=\"text\" name=\"idioma\" id=\"idioma\" class=\"form-control form-control-lg\" value=\"");
      out.print( jogo.getIdioma() );
      out.write("\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"mb-4\">\r\n");
      out.write("                                <label for=\"plataforma\" class=\"form-label fs-2\">Plataforma</label>\r\n");
      out.write("                                <input type=\"text\" name=\"plataforma\" id=\"plataforma\" class=\"form-control form-control-lg\" value=\"");
      out.print( jogo.getPlataforma() );
      out.write("\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"mb-4\">\r\n");
      out.write("                                <label for=\"classificacaoIndicativa\" class=\"form-label fs-2\">Classificação Indicativa</label>\r\n");
      out.write("                                <input type=\"text\" name=\"classificacaoIndicativa\" id=\"classificacaoIndicativa\" class=\"form-control form-control-lg\" value=\"");
      out.print( jogo.getClassificacaoIndicativa() );
      out.write("\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"mb-5\">\r\n");
      out.write("                                <label for=\"imagemJogo\" class=\"form-label fs-2\">Nova Arte do Jogo (opcional)</label>\r\n");
      out.write("                                <input type=\"file\" name=\"imagemJogo\" id=\"imagemJogo\" class=\"form-control form-control-lg\" accept=\"image/*\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"btn-center\">\r\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-success fs-5\">Atualizar Jogo</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
